"""Persistent planning and task management for autonomous coding work.

``plan.json`` at the project root is the authoritative plan state; see
:mod:`planning.store` for the data model and :class:`PlanStore`.
"""

from .store import (
    PLAN_ABANDONED,
    PLAN_ACTIVE,
    PLAN_COMPLETED,
    PLAN_STATUSES,
    PLAN_VERSION,
    TASK_BLOCKED,
    TASK_DONE,
    TASK_IN_PROGRESS,
    TASK_PENDING,
    TASK_SKIPPED,
    TASK_STATUSES,
    Checkpoint,
    Phase,
    Plan,
    PlanError,
    PlanStore,
    TestResult,
    Task,
    build_phases,
    git_checkpoint,
    phase_status,
    plan_from_dict,
    plan_progress,
    plan_to_dict,
    render_plan,
    render_plan_md,
    summarize_plan,
    task_by_id,
)

__all__ = [
    "PLAN_ABANDONED",
    "PLAN_ACTIVE",
    "PLAN_COMPLETED",
    "PLAN_STATUSES",
    "PLAN_VERSION",
    "TASK_BLOCKED",
    "TASK_DONE",
    "TASK_IN_PROGRESS",
    "TASK_PENDING",
    "TASK_SKIPPED",
    "TASK_STATUSES",
    "Checkpoint",
    "Phase",
    "Plan",
    "PlanError",
    "PlanStore",
    "TestResult",
    "Task",
    "build_phases",
    "git_checkpoint",
    "phase_status",
    "plan_from_dict",
    "plan_progress",
    "plan_to_dict",
    "render_plan",
    "render_plan_md",
    "summarize_plan",
    "task_by_id",
]
